"""
Batch Execution Orchestrator — BeforeAll Pattern
One browser. One login. N scenarios run sequentially.
This is the preferred execution path for "Run All" / batch test runs.
"""
from __future__ import annotations
import asyncio
import os
import time
from datetime import datetime
from typing import Any

import structlog
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.db.models import (
    ExecutionRun, ExecutionStep, ExecutionLog, ExecutionPlan,
    Environment, Credential, Scenario, ExecutionReport,
    ExecutionStatus, StepStatus, RiskLevel,
)
from app.execution.browser_manager import BrowserManager
from app.execution.executor import ExecutionOrchestrator
from app.execution.plan_runner import PlanRunner, StepExecutionResult
from app.execution.validation_engine import ValidationEngine
from app.execution.state_machine import WorkflowStateMachine
from app.execution.ui_transition_engine import UITransitionEngine
from app.execution.safety_guardrails import SafetyGuardrails
from app.execution.test_data_engine import TestDataEngine
from app.execution.confidence_engine import ConfidenceEngine
from app.execution.observability import ObservabilityLayer
from app.intelligence.failure_analyzer import FailureAnalyzer
from app.intelligence.scenario_planner import ScenarioPlanner
from app.execution.intent_orchestrator import IntentOrchestrator
from app.realtime.manager import connection_manager
from config import settings

log = structlog.get_logger()


class BatchExecutionOrchestrator:
    """
    Executes a list of scenarios sharing one browser session:
      - BeforeAll: navigate + login once
      - For each scenario: execute plan steps, record results, generate report
      - AfterAll: quit browser

    This avoids N redundant logins (critical for YLIMS with 90s Angular bootstrap).
    """

    def __init__(self, db: AsyncSession, main_loop=None):
        self.db = db
        self.main_loop = main_loop
        self._single = ExecutionOrchestrator(db, main_loop)
        self.failure_analyzer = FailureAnalyzer()

    async def execute_batch(self, run_ids: list[str]) -> None:
        """Main entry point — called by background batch job."""
        if not run_ids:
            return

        log.info("Starting batch execution", count=len(run_ids), run_ids=run_ids[:5])

        # Load all runs up front
        runs = []
        for rid in run_ids:
            run = await self._single._load_run(rid)
            if run:
                runs.append(run)
            else:
                log.warning("Batch: run not found", run_id=rid)

        if not runs:
            return

        # Load shared context from the first run
        first_run = runs[0]
        env = await self._single._load_environment(first_run.environment_id)
        scenario = await self._single._load_scenario(first_run.scenario_id)
        app_id = scenario.application_id if scenario else None
        credential = await self._single._load_credential(first_run.credential_id, app_id)

        if not env:
            for run in runs:
                await self._single._fail_run(run, "Environment not found")
            return

        # ── Phase 1: Pre-generate all AI plans BEFORE launching the browser ────
        # Doing plan generation during execution (while the browser is running) doubles
        # Azure rate-limit pressure. Pre-generating sequentially with gaps avoids 429s.
        await self._emit_batch_event("batch_started", run_ids, {
            "count": len(run_ids),
            "environment": env.name,
        })

        def _plan_is_trivial(plan) -> bool:
            """Return True if the plan is a fallback/trivial plan that needs AI regeneration."""
            if not plan:
                return True
            # KG-recorded plans are never trivial — they contain exact selectors from exploration
            # and must never be regenerated by AI (that would replace real selectors with guesses).
            if plan.created_by_model == "kg_recorded":
                return False
            if plan.created_by_model == "fallback":
                return True
            qa_reasoning = plan.plan_data.get("qa_reasoning", "")
            if qa_reasoning.startswith("Fallback plan"):
                return True
            # 5 or fewer steps = trivial fallback (screenshot, navigate, wait, screenshot, screenshot)
            if len(plan.plan_data.get("steps", [])) <= 5:
                return True
            return False

        for pre_idx, pre_run in enumerate(runs):
            pre_plan = await self._single._load_plan(pre_run.plan_id)
            if not _plan_is_trivial(pre_plan):
                continue  # already has a real plan — skip

            pre_scenario = await self._single._load_scenario(pre_run.scenario_id)
            if not pre_scenario:
                continue

            if pre_idx > 0:
                await asyncio.sleep(35)   # rate-limit cooldown between scenarios (Azure TPM quota resets every ~60s)

            # Try to generate a real AI plan — up to 3 attempts with cooldown on retry
            MAX_ATTEMPTS = 3
            for attempt in range(1, MAX_ATTEMPTS + 1):
                await self._log_batch(pre_run.id, "INFO", "execution",
                    f"[{pre_idx+1}/{len(runs)}] Generating AI plan: {pre_scenario.title[:60]}"
                    + (f" (attempt {attempt}/{MAX_ATTEMPTS})" if attempt > 1 else ""))
                try:
                    planner = ScenarioPlanner(self.db)
                    ai_plan = await asyncio.wait_for(
                        planner.generate_plan(pre_scenario, pre_plan.execution_mode if pre_plan else "functional"),
                        timeout=180.0,
                    )
                    pre_run.plan_id = ai_plan.id
                    await self.db.commit()
                    ai_reasoning = ai_plan.plan_data.get("qa_reasoning", "")
                    is_fallback = ai_reasoning.startswith("Fallback plan")
                    n_steps = len(ai_plan.plan_data.get("steps", []))

                    if not is_fallback and n_steps > 5:
                        # Real AI plan generated successfully
                        await self._log_batch(pre_run.id, "INFO", "execution",
                            f"[{pre_idx+1}/{len(runs)}] AI plan ready — "
                            f"{n_steps} steps, type: {ai_plan.plan_data.get('workflow_type', '?')}")
                        break
                    else:
                        # AI returned a fallback or trivially short plan
                        err_detail = ai_reasoning[len("Fallback plan — "):][: 120] if is_fallback else f"only {n_steps} steps"
                        if attempt < MAX_ATTEMPTS:
                            await self._log_batch(pre_run.id, "WARNING", "execution",
                                f"[{pre_idx+1}/{len(runs)}] AI plan is trivial ({err_detail}) — retrying in 30s")
                            await asyncio.sleep(30)
                        else:
                            await self._log_batch(pre_run.id, "ERROR", "execution",
                                f"[{pre_idx+1}/{len(runs)}] AI plan failed after {MAX_ATTEMPTS} attempts: {err_detail}")

                except (asyncio.TimeoutError, asyncio.CancelledError):
                    if attempt < MAX_ATTEMPTS:
                        await self._log_batch(pre_run.id, "WARNING", "execution",
                            f"[{pre_idx+1}/{len(runs)}] AI plan timed out (attempt {attempt}) — retrying in 30s")
                        await asyncio.sleep(30)
                    else:
                        await self._log_batch(pre_run.id, "ERROR", "execution",
                            f"[{pre_idx+1}/{len(runs)}] AI plan timed out after {MAX_ATTEMPTS} attempts — execution will be skipped")
                except Exception as plan_err:
                    err_msg = str(plan_err)[:120]
                    if attempt < MAX_ATTEMPTS:
                        await self._log_batch(pre_run.id, "WARNING", "execution",
                            f"[{pre_idx+1}/{len(runs)}] AI plan error ({err_msg}) — retrying in 30s")
                        await asyncio.sleep(30)
                    else:
                        await self._log_batch(pre_run.id, "ERROR", "execution",
                            f"[{pre_idx+1}/{len(runs)}] AI plan failed after {MAX_ATTEMPTS} attempts: {err_msg}")

        # ── Phase 2: Launch browser + execute all plans ───────────────────────
        batch_start = datetime.utcnow()

        browser = None
        try:
            # ── BeforeAll: Launch browser + Login once ────────────────────────
            browser = BrowserManager.create(window_size=(1920, 1080))
            # Checkpoint AI validation is disabled in batch mode — each call hits the Azure
            # rate limit and 429s cascade across all scenarios in the batch.
            # Individual single-run execution still uses ValidationEngine.
            ui_engine = UITransitionEngine(browser)
            safety    = SafetyGuardrails(env.base_url)

            runner = PlanRunner(
                browser=browser,
                base_url=env.base_url,
                screenshots_dir=settings.SCREENSHOTS_DIR,
                run_id=run_ids[0],
                event_callback=lambda e, d: asyncio.create_task(
                    self._emit_event(e, run_ids[0], d)
                ),
                validation_engine=None,   # disabled — conserves rate limit for plan generation
                ui_engine=ui_engine,
                safety=safety,
            )

            await self._log_batch(run_ids[0], "INFO", "batch", "BeforeAll: logging in once for all scenarios")
            login_ok = await self._single._execute_login(
                runner=runner,
                browser=browser,
                app_id=app_id,
                credential=credential,
                env=env,
                run_id=run_ids[0],
            )

            if not login_ok:
                fail_reason = "BeforeAll login failed — could not authenticate before running scenarios"
                for run in runs:
                    # Write a log entry for every run so users can see WHY it failed
                    entry = ExecutionLog(
                        run_id=run.id,
                        level="ERROR",
                        category="login",
                        message=fail_reason,
                        extra={},
                    )
                    self.db.add(entry)
                    await self._single._fail_run(run, fail_reason)
                await self.db.commit()
                await self._emit_batch_event("batch_failed", run_ids, {
                    "reason": fail_reason,
                    "total": len(runs),
                    "failed": len(runs),
                })
                return

            await self._log_batch(run_ids[0], "SUCCESS", "batch",
                f"Login successful — executing {len(runs)} scenarios")

            # Dependency-aware skip: track which module create-operations succeeded.
            # Key: module_id → True (create passed) / False (create failed).
            # Downstream update/delete scenarios for a module are skipped if create failed —
            # they would fail for the wrong reason (no record to act on).
            _module_create_ok: dict[str, bool] = {}

            # ── Execute each scenario ─────────────────────────────────────────
            for idx, run in enumerate(runs):
                # Between scenarios: soft-reset to app home via Angular hash nav.
                # This avoids carrying over page state from the previous scenario
                # while preserving the in-memory JWT (no full page reload).
                if idx > 0:
                    try:
                        browser.execute_script("window.location.hash = '/';")
                        await asyncio.sleep(1.5)
                    except Exception:
                        pass

                # Mark THIS run (and only this run) as RUNNING now
                run.status = ExecutionStatus.RUNNING
                run.started_at = datetime.utcnow()
                await self.db.commit()

                await self._emit_event("run_started", run.id, {
                    "scenario_id": run.scenario_id,
                    "plan_id": run.plan_id,
                    "environment": env.name,
                    "batch_index": idx + 1,
                    "batch_total": len(runs),
                })

                plan = await self._single._load_plan(run.plan_id)
                if not plan:
                    await self._single._fail_run(run, "Execution plan not found")
                    continue

                # Plans were pre-generated in Phase 1 — just reload the (possibly updated) plan
                scenario_obj = await self._single._load_scenario(run.scenario_id)
                scenario_title = scenario_obj.title if scenario_obj else plan.plan_data.get("workflow", "Scenario")
                # Reload plan in case Phase 1 updated run.plan_id
                plan = await self._single._load_plan(run.plan_id) or plan

                # ── Dependency-aware skip ─────────────────────────────────────
                # If a create scenario for this module already failed, skip downstream
                # update/delete scenarios — they'd fail because there's no record to act on.
                if scenario_obj and scenario_obj.module_id:
                    _wf_type = (plan.plan_data.get("workflow_type") or "").lower()
                    _mid = scenario_obj.module_id
                    _is_downstream = _wf_type in ("crud_update", "crud_delete", "update", "delete")
                    if _is_downstream and _module_create_ok.get(_mid) is False:
                        skip_reason = (
                            f"Dependency skip — create scenario for this module failed; "
                            f"update/delete would fail because no record exists."
                        )
                        await self._log_batch(run.id, "WARNING", "execution",
                            f"[{idx+1}/{len(runs)}] SKIPPED (dependency) — {skip_reason}")
                        run.status = ExecutionStatus.FAILED
                        run.error_message = skip_reason
                        run.completed_at = datetime.utcnow()
                        await self.db.commit()
                        continue

                # Guard: refuse to execute a trivial/fallback plan and pretend it passed.
                # KG-recorded plans are always executable — skip the guard for them.
                plan_reasoning = plan.plan_data.get("qa_reasoning", "")
                plan_steps = plan.plan_data.get("steps", [])
                is_kg_plan = plan.created_by_model == "kg_recorded"
                if not is_kg_plan and (plan_reasoning.startswith("Fallback plan") or len(plan_steps) <= 5):
                    reason = (
                        "AI plan generation failed — " +
                        plan_reasoning[len("Fallback plan — "):][: 200]
                        if plan_reasoning.startswith("Fallback plan")
                        else f"Only {len(plan_steps)} trivial steps available — real AI plan was not generated"
                    )
                    await self._log_batch(run.id, "ERROR", "execution",
                        f"[{idx+1}/{len(runs)}] SKIPPED — AI plan unavailable: {reason[:200]}. "
                        "Check Azure OpenAI rate limits and retry the batch.")
                    await self._single._fail_run(run, f"AI plan unavailable: {reason[:200]}")
                    continue

                # Update runner for this specific run — fresh per-scenario state
                runner.run_id = run.id
                runner.event_callback = lambda e, d, rid=run.id: asyncio.create_task(
                    self._emit_event(e, rid, d)
                )
                runner.state_machine = WorkflowStateMachine()
                runner.test_data     = TestDataEngine()
                runner.confidence    = ConfidenceEngine(run.id)
                runner.observability = ObservabilityLayer(run.id)

                # Build intent context per scenario — entity tracking, workflow classification
                _orchestrator = IntentOrchestrator(self.db)
                _exec_ctx = await _orchestrator.prepare(
                    scenario=scenario_obj,
                    plan_data=plan.plan_data,
                    env_base_url=env.base_url,
                )
                runner.entity_tracker = _exec_ctx.entity_tracker

                await self._log_batch(run.id, "INFO", "execution",
                    f"[{idx+1}/{len(runs)}] Executing: {scenario_title}")

                try:
                    step_results = await runner.execute_plan(plan.plan_data)
                    _intent_summary = await _orchestrator.post_execute(step_results, _exec_ctx)

                    # Persist steps
                    await self._single._persist_steps(
                        run.id, plan.plan_data.get("steps", []), step_results
                    )

                    summary = self._single._compute_summary(step_results)
                    run.total_steps = summary["total"]
                    run.passed_steps = summary["passed"]
                    run.failed_steps = summary["failed"]
                    run.healed_steps = summary["healed"]
                    run.status = (
                        ExecutionStatus.COMPLETED if summary["failed"] == 0
                        else ExecutionStatus.FAILED
                    )
                    run.completed_at = datetime.utcnow()
                    await self.db.commit()

                    # Record create outcome for dependency-aware skip of downstream scenarios
                    if scenario_obj and scenario_obj.module_id:
                        _wf = (plan.plan_data.get("workflow_type") or "").lower()
                        if _wf in ("crud_create", "create", "crud"):
                            _module_create_ok[scenario_obj.module_id] = (summary["failed"] == 0)

                    # Generate report — capped at 60s so a slow AI call never blocks the batch
                    checkpoint_results, workflow_context = self._single._extract_execution_intelligence(
                        plan.plan_data, step_results
                    )
                    workflow_context["entity_lifecycle"] = _intent_summary.get("entity_lifecycle", {})
                    workflow_context["business_outcomes_confirmed"] = _intent_summary.get("business_outcomes_confirmed", True)
                    workflow_context["primary_entity"] = _exec_ctx.primary_entity
                    try:
                        await asyncio.wait_for(
                            self._single._generate_report(
                                run, plan.plan_data, step_results, summary,
                                checkpoint_results=checkpoint_results,
                                workflow_context=workflow_context,
                            ),
                            timeout=60.0,
                        )
                    except (asyncio.TimeoutError, asyncio.CancelledError):
                        await self._log_batch(run.id, "WARNING", "execution",
                            "Report generation timed out — skipping report for this scenario")
                    except Exception as report_err:
                        await self._log_batch(run.id, "WARNING", "execution",
                            f"Report generation failed: {str(report_err)[:200]}")

                    await self._emit_event("run_completed", run.id, {
                        "status": run.status.value,
                        "passed": summary["passed"],
                        "failed": summary["failed"],
                        "total": summary["total"],
                        "batch_index": idx + 1,
                        "batch_total": len(runs),
                        "workflow_type": plan.plan_data.get("workflow_type", ""),
                        "phases_completed": workflow_context.get("phases_completed", []),
                        "phases_failed": workflow_context.get("phases_failed", []),
                        "checkpoints_total": len(checkpoint_results),
                        "checkpoints_passed": sum(1 for cp in checkpoint_results if cp.get("passed")),
                    })

                    await self._log_batch(run.id, "INFO", "execution",
                        f"[{idx+1}/{len(runs)}] Done — "
                        f"{summary['passed']}/{summary['total']} steps passed")

                    log.info("Batch run completed",
                        run_id=run.id, status=run.status.value,
                        passed=summary["passed"], failed=summary["failed"])

                except (Exception, asyncio.CancelledError) as step_err:
                    err_msg = str(step_err)[:300]
                    log.exception("Batch scenario crashed", run_id=run.id, error=err_msg)
                    await self._log_batch(run.id, "ERROR", "execution",
                        f"[{idx+1}/{len(runs)}] Scenario crashed: {err_msg}")
                    await self._single._fail_run(run, f"Execution crashed: {err_msg}")
                    # Don't abort the whole batch — continue with next scenario

            # ── Batch summary ─────────────────────────────────────────────────
            completed = sum(1 for r in runs if r.status == ExecutionStatus.COMPLETED)
            failed = sum(1 for r in runs if r.status == ExecutionStatus.FAILED)
            await self._emit_batch_event("batch_completed", run_ids, {
                "total": len(runs),
                "completed": completed,
                "failed": failed,
                "duration_seconds": (datetime.utcnow() - batch_start).total_seconds(),
            })
            log.info("Batch execution done",
                total=len(runs), completed=completed, failed=failed)

        except (Exception, asyncio.CancelledError) as e:
            err_msg = f"Batch crashed: {str(e)[:300]}"
            log.exception("Batch execution crashed", error=str(e))
            for run in runs:
                if run.status == ExecutionStatus.RUNNING:
                    entry = ExecutionLog(
                        run_id=run.id, level="ERROR", category="batch",
                        message=err_msg, extra={},
                    )
                    self.db.add(entry)
                    await self._single._fail_run(run, err_msg)
            try:
                await self.db.commit()
            except Exception:
                pass
            await self._emit_batch_event("batch_failed", run_ids, {
                "reason": err_msg,
                "total": len(runs),
                "failed": sum(1 for r in runs if r.status == ExecutionStatus.FAILED),
            })
        finally:
            if browser:
                browser.quit()

    # ─── Event / log helpers ──────────────────────────────────────────────────

    async def _log_batch(self, run_id: str, level: str, category: str, message: str):
        import uuid as _uuid_mod
        from datetime import timezone
        log_id = str(_uuid_mod.uuid4())
        ts = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
        # Emit WS first so the UI sees it immediately
        await self._emit_event("run_log", run_id, {
            "id": log_id,
            "level": level,
            "category": category,
            "message": message,
            "timestamp": ts,
        })
        entry = ExecutionLog(
            id=log_id,
            run_id=run_id,
            level=level,
            category=category,
            message=message,
            extra={},
        )
        self.db.add(entry)
        await self.db.commit()

    async def _emit_event(self, event: str, run_id: str, data: dict):
        msg = {"event": event, "run_id": run_id, **data}
        try:
            current_loop = asyncio.get_running_loop()
            if self.main_loop and self.main_loop is not current_loop and self.main_loop.is_running():
                asyncio.run_coroutine_threadsafe(
                    connection_manager.broadcast_json(msg), self.main_loop
                )
            else:
                await connection_manager.broadcast_json(msg)
        except Exception:
            pass

    async def _emit_batch_event(self, event: str, run_ids: list[str], data: dict):
        msg = {"event": event, "run_ids": run_ids, **data}
        try:
            current_loop = asyncio.get_running_loop()
            if self.main_loop and self.main_loop is not current_loop and self.main_loop.is_running():
                asyncio.run_coroutine_threadsafe(
                    connection_manager.broadcast_json(msg), self.main_loop
                )
            else:
                await connection_manager.broadcast_json(msg)
        except Exception:
            pass
