"""add_discover_only_to_explore_sessions

Revision ID: 5c9061208463
Revises: a1b2c3d4e5f6
Create Date: 2026-06-09 10:16:14.391664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9061208463'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_app_knowledge_graph', 'applications', 'knowledge_graphs', ['knowledge_graph_id'], ['id'], use_alter=True)
    op.add_column('explore_sessions', sa.Column('discover_only', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('explore_sessions', 'discover_only')
    op.drop_constraint('fk_app_knowledge_graph', 'applications', type_='foreignkey')
    # ### end Alembic commands ###
