"""initial_schema

Revision ID: dea1cd91af55
Revises: 
Create Date: 2026-05-22 21:42:11.991179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea1cd91af55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('app_type', sa.String(length=100), nullable=True),
    sa.Column('explore_mode', sa.Enum('FULL', 'SMART', 'SKIP', name='exploremode'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('knowledge_graph_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['knowledge_graph_id'], ['knowledge_graphs.id'], name='fk_app_knowledge_graph', use_alter=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='workspacerole'), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_table('ai_memory_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('MODULE', 'PAGE', 'WORKFLOW', 'SELECTOR', 'FIELD', 'EXECUTION_LEARNING', 'DYNAMIC_BEHAVIOR', name='memorykind'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chroma_doc_id', sa.String(length=512), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_memory_chunks_application_id'), 'ai_memory_chunks', ['application_id'], unique=False)
    op.create_index(op.f('ix_ai_memory_chunks_kind'), 'ai_memory_chunks', ['kind'], unique=False)
    op.create_table('application_modules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url_pattern', sa.String(length=1024), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('semantic_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['application_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('env_type', sa.Enum('DEVELOPMENT', 'STAGING', 'PRODUCTION', 'CUSTOM', name='environmenttype'), nullable=True),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('explore_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('mode', sa.Enum('FULL', 'SMART', 'SKIP', name='exploremode'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'WAITING_HUMAN', 'COMPLETED', 'FAILED', 'CANCELLED', name='explorestatus'), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('pages_discovered', sa.Integer(), nullable=True),
    sa.Column('modules_discovered', sa.Integer(), nullable=True),
    sa.Column('workflows_discovered', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('preference_key', sa.String(length=512), nullable=False),
    sa.Column('preference_value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_pages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_pattern', sa.String(length=1024), nullable=True),
    sa.Column('page_type', sa.String(length=100), nullable=True),
    sa.Column('semantic_map', sa.JSON(), nullable=True),
    sa.Column('forms', sa.JSON(), nullable=True),
    sa.Column('tables', sa.JSON(), nullable=True),
    sa.Column('navigation_links', sa.JSON(), nullable=True),
    sa.Column('dynamic_behaviors', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['application_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_type', sa.String(length=100), nullable=True),
    sa.Column('stages', sa.JSON(), nullable=True),
    sa.Column('entry_point', sa.JSON(), nullable=True),
    sa.Column('success_indicators', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['application_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=512), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('auth_blueprint', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('explore_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['explore_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explore_logs_session_id'), 'explore_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_explore_logs_timestamp'), 'explore_logs', ['timestamp'], unique=False)
    op.create_table('knowledge_graphs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('explore_session_id', sa.String(), nullable=True),
    sa.Column('graph_data', sa.JSON(), nullable=False),
    sa.Column('modules_count', sa.Integer(), nullable=True),
    sa.Column('pages_count', sa.Integer(), nullable=True),
    sa.Column('workflows_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['explore_session_id'], ['explore_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='scenariopriority'), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('module_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['application_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('execution_mode', sa.String(length=100), nullable=True),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('semantic_intent', sa.JSON(), nullable=True),
    sa.Column('workflow_stages', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('estimated_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_by_model', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semantic_elements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('page_id', sa.String(), nullable=False),
    sa.Column('semantic_label', sa.String(length=512), nullable=False),
    sa.Column('element_type', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('workflow_stage', sa.String(length=255), nullable=True),
    sa.Column('selectors', sa.JSON(), nullable=True),
    sa.Column('healing_strategies', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('network_triggers', sa.JSON(), nullable=True),
    sa.Column('dynamic_reveals', sa.JSON(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['application_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('environment_id', sa.String(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PARTIAL', name='executionstatus'), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('passed_steps', sa.Integer(), nullable=True),
    sa.Column('failed_steps', sa.Integer(), nullable=True),
    sa.Column('skipped_steps', sa.Integer(), nullable=True),
    sa.Column('healed_steps', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('screenshot_paths', sa.JSON(), nullable=True),
    sa.Column('video_path', sa.String(length=2048), nullable=True),
    sa.Column('browser_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['execution_plans.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selector_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('element_id', sa.String(), nullable=False),
    sa.Column('strategies', sa.JSON(), nullable=False),
    sa.Column('best_strategy_index', sa.Integer(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('healing_history', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['semantic_elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('element_id')
    )
    op.create_table('execution_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('rca_analysis', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('execution_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_step', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'SKIPPED', 'HEALED', name='stepstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=2048), nullable=True),
    sa.Column('healing_triggered', sa.Boolean(), nullable=True),
    sa.Column('healing_attempts', sa.JSON(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_screenshot_path', sa.String(length=2048), nullable=True),
    sa.Column('state_before', sa.JSON(), nullable=True),
    sa.Column('state_after', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('execution_run_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('selected_option', sa.JSON(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('is_saved_as_preference', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['execution_run_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['explore_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['execution_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_run_id'), 'execution_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_execution_logs_timestamp'), 'execution_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_logs_timestamp'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_run_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_table('human_decisions')
    op.drop_table('execution_steps')
    op.drop_table('execution_reports')
    op.drop_table('selector_memories')
    op.drop_table('execution_runs')
    op.drop_table('semantic_elements')
    op.drop_table('execution_plans')
    op.drop_table('scenarios')
    op.drop_table('knowledge_graphs')
    op.drop_index(op.f('ix_explore_logs_timestamp'), table_name='explore_logs')
    op.drop_index(op.f('ix_explore_logs_session_id'), table_name='explore_logs')
    op.drop_table('explore_logs')
    op.drop_table('credentials')
    op.drop_table('application_workflows')
    op.drop_table('application_pages')
    op.drop_table('workspace_preferences')
    op.drop_table('explore_sessions')
    op.drop_table('environments')
    op.drop_table('application_modules')
    op.drop_index(op.f('ix_ai_memory_chunks_kind'), table_name='ai_memory_chunks')
    op.drop_index(op.f('ix_ai_memory_chunks_application_id'), table_name='ai_memory_chunks')
    op.drop_table('ai_memory_chunks')
    op.drop_table('workspace_members')
    op.drop_table('applications')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
